import "./globals.css";
import { ReactLenis } from "lenis/react";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "HUMMANA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <ReactLenis root options={{ duration: 1.2, syncTouch: true }}>
          <Navbar />
          <div id="total-wrapper">{children}</div>
        </ReactLenis>
      </body>
    </html>
  );
}
